# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import editormd.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=editormd.models.get_file_path)),
                ('author', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
