# Generated by Django 2.1 on 2018-11-27 10:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='分类名称')),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='分类网址')),
                ('sn', models.IntegerField(null=True, verbose_name='排序')),
                ('intro', models.CharField(max_length=100, verbose_name='分类简介')),
                ('visible', models.BooleanField(default=True, verbose_name='显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('keywords', models.CharField(blank=True, max_length=80, null=True, verbose_name='关键字')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('keywords', models.CharField(blank=True, max_length=80, null=True, verbose_name='关键字')),
                ('slug', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='网址')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='缩略图')),
                ('abstract', models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要')),
                ('content', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='内容')),
                ('html_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='html内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '发布')], default='p', max_length=1, verbose_name='状态')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.Category', verbose_name='归属分类')),
            ],
            options={
                'verbose_name': '详情',
                'verbose_name_plural': '详情',
                'ordering': ['-last_modified_time'],
            },
        ),
    ]
