# Generated by Django 2.1 on 2018-12-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20181204_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescontent',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='缩略图'),
        ),
    ]
