# Generated by Django 2.1 on 2018-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_suggest',
            field=models.BooleanField(default=False, verbose_name='推荐'),
        ),
    ]
