# Generated by Django 2.1 on 2018-11-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='star',
            field=models.IntegerField(default=3, verbose_name='评星'),
        ),
        migrations.AddField(
            model_name='course',
            name='star_eval_num',
            field=models.IntegerField(default=1, verbose_name='评星人数'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course', verbose_name='归属课程'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='column',
            name='created_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='config',
            name='theme',
            field=models.CharField(choices=[('bootstrap', 'bootstrap'), ('litera', 'litera'), ('litera', 'litera'), ('materia', 'materia'), ('stadstone', 'stadstone'), ('yeti', 'yeti')], max_length=20, verbose_name='模板'),
        ),
    ]
