# Generated by Django 2.1 on 2018-11-26 09:15

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20181126_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='html_content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
    ]
