# Generated by Django 2.1 on 2018-10-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20181030_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='show_in_nav',
            field=models.BooleanField(default=False, verbose_name='导航显示'),
        ),
    ]
