# Generated by Django 2.1 on 2018-10-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_column_show_in_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='abstract',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='column',
            name='intro',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='栏目简介'),
        ),
        migrations.AlterField(
            model_name='course',
            name='intro',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='课程简介'),
        ),
    ]
