# Generated by Django 2.1 on 2018-10-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20181031_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='visible',
        ),
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.IntegerField(choices=[('d', '草稿'), ('p', '发布')], default=1, verbose_name='状态'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='intro',
            field=models.CharField(max_length=100, verbose_name='课程简介'),
        ),
    ]
