# Generated by Django 2.1 on 2018-11-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='thumbnail',
            new_name='pic',
        ),
    ]
