# Generated by Django 2.1 on 2018-11-09 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20181106_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='项目')),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('visible', models.BooleanField(default=True, verbose_name='显示')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='course.Chapter')),
            ],
            options={
                'ordering': ('created_time',),
            },
        ),
    ]
