# Generated by Django 2.1 on 2018-12-03 10:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='链接')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='关键字')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_related', to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='courses.Category', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='链接')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='关键字')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('d', '草稿'), ('p', '发布'), ('e', '删除')], default='p', max_length=1, verbose_name='状态')),
                ('md_content', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='内容')),
                ('html_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '内容',
                'verbose_name_plural': '内容',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='链接')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='关键字')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='缩略图')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.Category', verbose_name='所属分类')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_related', to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='链接')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='关键字')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.Course', verbose_name='所属课程')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_related', to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.Module', verbose_name='所属模块'),
        ),
        migrations.AddField(
            model_name='content',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_related', to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
    ]
