# Generated by Django 2.1 on 2018-12-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_suggest',
            field=models.BooleanField(default=False),
        ),
    ]
