# Generated by Django 2.1 on 2018-12-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='module',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='content',
            name='module',
        ),
        migrations.AddField(
            model_name='content',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.Course', verbose_name='所属模块'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
