# Generated by Django 2.1 on 2018-12-04 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_auto_20181203_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('visible', models.BooleanField(default=True, verbose_name='显示')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评论内容')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
        migrations.AddField(
            model_name='category',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
        migrations.AddField(
            model_name='course',
            name='stars',
            field=models.IntegerField(default=3, verbose_name='评星'),
        ),
        migrations.AddField(
            model_name='course',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='显示'),
        ),
        migrations.AddField(
            model_name='comment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.Lesson', verbose_name='所评章节'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_related', to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
    ]
