# Generated by Django 2.1 on 2018-12-04 07:11

import courses.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20181204_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '教程分类', 'verbose_name_plural': '教程分类'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '教程', 'verbose_name_plural': '教程'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': '教程内容', 'verbose_name_plural': '教程内容'},
        ),
        migrations.AlterField(
            model_name='course',
            name='is_suggest',
            field=models.BooleanField(default=False, verbose_name='推荐课程'),
        ),
        migrations.AlterField(
            model_name='course',
            name='order',
            field=courses.fields.OrderField(blank=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.Course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=courses.fields.OrderField(blank=True, verbose_name='排序'),
        ),
    ]
